### ISSUE TITLE
Rename the repo to FabAcademy-Resources

### ISSUE THREAD

**Issue by fibasile** [Academany/FabAcademany-ExtraResources#1]
I did setup the index page and redirects

http://docs.fabacademy.org

For this repo, I'd send people straight to github. If needed we could put an index.html with resources listing, but I leave it up to you, even a README.md with a list is fine for me.

Soon we'll also have fab.academany.org pointing at the same page.

**Comment by fibasile** [comment]
I just noticed the repo is in gitbook format, does it make sense?

**Comment by EDUARDOCHAMORRO** [comment]
We made it with the idea of having the same looking as
Assesment/Tutorials/etc. To have everything equal, so it is easier to
maintain/ contribute.

**Comment by fibasile** [comment]
Ok fine for me. Can we rename the repository, I guess there are some links to be updated in the tutorials?

**Comment by EDUARDOCHAMORRO** [comment]
Fixed

**Comment by TheBeachLab** [comment]
The repository is still not renamed and in confusing FabAcademy and FabAcademany. Now that there are not many users let's do that
